import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { adaptCodexContent } from "./codex-compatibility.mjs";

const skills = [
  { name: "grill-me", userInvoked: true },
  { name: "grilling", userInvoked: false },
  { name: "domain-modeling", userInvoked: false },
  { name: "prototype", userInvoked: false },
];
const adapt = (content, options = {}) => adaptCodexContent({ skillName: "grill-me", relativePath: "SKILL.md", content, skills, ...options });

test("dispatch uses packaged model-invoked siblings and preserves human gates", () => {
  const result = adapt('---\nname: grill-me\ndescription: test\n---\nCall the Skill tool twice, for "grilling" and "domain-modeling".');
  assert.match(result, /Read and follow both \[grilling\]\(\.\.\/grilling\/SKILL.md\) and \[domain-modeling\]/);
  assert.match(result, /only after the user explicitly selects it/);
  assert.throws(() => adapt('Call the Skill tool with "grill-me".'), /user-only/);
  assert.throws(() => adapt('Call the Skill tool with "missing".'), /Unknown/);
  assert.throws(() => adapt("Invoke the Skill tool for something else."), /Unadapted/);
});

test("skill labels are namespaced without rewriting routes, URLs or resources", () => {
  assert.equal(adapt("Use /grilling or `/prototype`. Keep /prototype/demo, ./prototype, ../grilling/SKILL.md and https://example.com/grilling.", { relativePath: "reference.md" }),
    "Use $mattpocock-skills:grilling or `$mattpocock-skills:prototype`. Keep /prototype/demo, ./prototype, ../grilling/SKILL.md and https://example.com/grilling.");
  assert.equal(adapt("# Generated by /wizard", { relativePath: "template.sh" }), "# Generated by /wizard");
});

test("only the Claude invocation field is omitted from generated frontmatter", () => {
  const source = '---\nname: grill-me\ndisable-model-invocation: true\ndescription: "Keep this quoting"\nargument-hint: "Keep this hint"\n---\n\nExample: disable-model-invocation: true\n';
  const result = adapt(source);
  assert.ok(result.startsWith('---\nname: grill-me\ndescription: "Keep this quoting"\nargument-hint: "Keep this hint"\n---\n'));
  assert.match(result, /Example: disable-model-invocation: true/);
  assert.match(source, /^disable-model-invocation: true$/m);
  const yaml = 'interface:\n  display_name: "Grill Me"\npolicy:\n  allow_implicit_invocation: false\n';
  assert.equal(adapt(yaml, { relativePath: "agents/openai.yaml" }), yaml);
});

test("real workflow adapters preserve setup, dispatch and delegation controls", () => {
  const manifest = JSON.parse(readFileSync(new URL("../.claude-plugin/plugin.json", import.meta.url)));
  const sources = manifest.skills.map((path) => {
    const content = readFileSync(new URL(`../${path}/SKILL.md`, import.meta.url), "utf8");
    return { name: path.split("/").at(-1), userInvoked: /disable-model-invocation: true/.test(content), content };
  });
  const output = new Map(sources.map((source) => [source.name, adaptCodexContent({
    skillName: source.name, relativePath: "SKILL.md", content: source.content, skills: sources,
  })]));
  assert.match(output.get("implement"), /\[tdd\]\(\.\.\/tdd\/SKILL.md\)/);
  assert.match(output.get("implement"), /\[code-review\]\(\.\.\/code-review\/SKILL.md\)/);
  assert.match(output.get("setup-matt-pocock-skills"), /Edit `AGENTS.md` when it exists/);
  assert.match(output.get("setup-matt-pocock-skills"), /Show the exact draft and obtain the confirmation/);
  assert.match(output.get("research"), /already the research subagent, perform the research below yourself/);
  assert.match(output.get("wayfinder"), /a ticket's Notes never grant invocation permission/);
  for (const source of sources) {
    assert.doesNotMatch(output.get(source.name).split("---")[1], /disable-model-invocation:/);
    assert.equal(/only after the user explicitly selects it/.test(output.get(source.name)), source.userInvoked);
    const canonicalPath = manifest.skills.find((path) => path.endsWith(`/${source.name}`));
    assert.equal(readFileSync(new URL(`../${canonicalPath}/SKILL.md`, import.meta.url), "utf8"), source.content);
    assert.doesNotMatch(output.get(source.name), /Skill tool/);
  }
});
